import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "700"], // Add desired font weights
});

export const metadata: Metadata = {
  title: "Pengklasifikasi Lirik",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="id">
      <body
      className={`${poppins.variable} ${poppins.variable} antialiased`}
      >
      {children}
      </body>
    </html>
  );
}
